FROM node:23-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    nano \
    wget \
    curl \
    git \
    unzip \
    zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
RUN mkdir /app
COPY . /app
WORKDIR /app

# Install Bun
RUN npm i -g bun
RUN bun install && bun next telemetry disable && bun run build

# Expose port
EXPOSE 52522

CMD ["bun", "start", "--", "-H", "0.0.0.0", "-p", "52522"]