name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install Bun
        run: npm install -g bun

      - name: Build web
        working-directory: client
        run: bun install && bunx next build
